spring:
    application:
        name: opendata-crud
    datasource:
        url: "jdbc:mariadb://localhost:3306/pmr"
        username : root
        password: ""
        driver-class-name: org.mariadb.jdbc.Driver